# Generated by Django 3.0.7 on 2022-09-23 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Chat_Group',
        ),
    ]
