# Generated by Django 3.0.7 on 2022-09-23 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220923_0642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat_group',
            options={'verbose_name': 'Chat Group'},
        ),
    ]
